language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tempo-prototype' ]; then cd .. && eval "mv $currentfolder generator-tempo-prototype" && cd generator-tempo-prototype; fi
